services:

  app:
    container_name: growmate
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
      - rabbitmq3
      - influxdb
      - redis
    networks:
      - net

  postgresql:
    container_name: postgresql
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'

    networks:
      - net


  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - net

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    networks:
      - net

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDIS_USER: user
      REDIS_PASSWORD: secret
    networks:
      - net

networks:
  net:
    name: net
